# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 01c9810bd1a4598a04b92f33891aaee494be2e54b6653296d833a16a3edcb8053a3c369a9cc5d8039d6c0cad37bf91ba694ef63a7ea40a8b41feebb98618fba6

test:
  secret_key_base: ede2b2ebc9ee417f8a4eacd210f0912eadab7cea0cba52fd318abbaa8d459e95f522af5e9e167ead8f43b7fdbbb6b2dc688eec7ba4a5102a8f96c5a15ce8df94

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
